apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  labels:
    app: infoservice
  name: infoservice-vs
spec:
  gateways:
  - {{ .Values.componentGateway }}
  hosts:
  - infoservice.{{ .Values.domain }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: info.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: 80
