apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.clusterIssuer }}
  name: {{ .Release.Name }}
spec:
  ingressClassName: nginx
  rules:
  - host: infoservice.{{ .Values.domain }}
    http:
      paths:
      - backend:
          service:
            name: info
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - infoservice.{{ .Values.domain }}
    secretName: infoservice-tls
