apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-infoservice
  labels:
    app: {{ .Release.Name }}-infoservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-infoservice
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-infoservice
    spec:
      containers:
      - name: {{ .Release.Name }}-infoservice
        image: {{ include "serviceinventoryapi.dockerimage" . }}
        imagePullPolicy: {{ include "serviceinventoryapi.imagePullPolicy" . }}
        env:
        - name: SERVER_URL
          value: {{ .Values.serverUrl }}
        ports:
        - containerPort: 8638
